version: '3.8'

services:
  youtube-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-analyzer
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
      - ./db:/app/db
      - ./.env:/app/.env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s