classify_video:
  description: >
    Your task is to classify the YouTube video content based on its transcription.
    
    You will receive the transcription of the YouTube video as input.
    Here is the transcription:
    {transcript}
    
    Please classify this video into one of the following categories:
    - Technology
    - Business
    - Education
    - Health & Wellness
    - Science
    - Finance
    - Personal Development
    
    Provide a brief explanation for your classification choice, highlighting key terms or themes
    from the transcript that support your decision. If the video spans multiple categories,
    choose the most dominant one and mention the secondary categories in your explanation.

  expected_output: >
    A clear classification of the video into one of the specified categories, along with
    a brief explanation justifying the classification based on the transcript content.

summarize_content:
  description: >
    Your task is to create a comprehensive summary of the YouTube video based on its transcription.
    
    You will receive the transcription of the YouTube video as input.
    Here is the transcription:
    {transcript}
    
    Please create a well-structured summary with the following sections:
    1. Overall TL;DR (2-3 paragraphs)
    2. Key points and main ideas
    3. Important details and examples mentioned
    
    Your summary should be clear, concise, and capture all the essential information from the video.
    Focus on maintaining the core message while eliminating redundancy and less important details.

  expected_output: >
    A comprehensive, well-structured summary of the YouTube video with the requested sections.
    The summary should be clear, concise, and capture all the essential information.

analyze_content:
  description: >
    Your task is to analyze the YouTube video content based on its transcription and summary.
    
    You will receive the transcription of the YouTube video as input.
    Here is the transcription:
    {transcript}

    Use the summary from the Summarize Content task.
    
    Please analyze this content focusing on:
    1. The main product, service, or concept being discussed
    2. The target audience and their needs
    3. The unique value propositions presented
    4. Any technical details or specifications mentioned
    5. Potential applications or use cases
    
    Your analysis should be detailed and provide valuable insights for someone interested in this topic.
    Support your analysis with specific examples and quotes from the transcription.

  expected_output: >
    A detailed analysis of the YouTube video content focusing on the requested aspects.
    The analysis should include specific examples and quotes from the transcription to support your insights.

create_action_plan:
  description: >
    Your task is to create an actionable plan based on the YouTube video content.

    Use the transcript provided by the user for a better understanding of the video content.
    Here is the transcript:
    {transcript}

    Use the summary from the Summarize Content task.
    Use the analysis from the Analyze Content task.
    
    Based on this information, create a practical action plan with:
    1. 3-5 specific steps the user can take to apply the knowledge from the video
    2. Resources they might need to implement each step
    3. Expected outcomes from following this plan
    4. Potential challenges they might face and how to overcome them
    
    Your plan should be practical, specific, and immediately actionable.
    Make sure each step is clear and provides concrete guidance.

  expected_output: >
    A practical action plan with specific steps, resources, expected outcomes, and potential challenges.
    The plan should be immediately actionable and provide clear guidance for implementing the knowledge
    from the video. 

write_report:
  description: >
    Your task is to write a report based on the YouTube video content in Markdown format.
    
    Use the transcript provided by the user for a better understanding of the video content.
    Here is the transcript:
    {transcript}

    Use the classification from the Classify Video task.
    Use the summary from the Summarize Content task.
    Use the analysis from the Analyze Content task.
    Use the action plan from the Create Action Plan task.
    
    Please write a report with the following sections:
    1. Video Classification
    2. TL;DR of the video content
    3. Key points and main ideas
    4. Important details and examples mentioned
    5. Analysis of the video content
    6. Action plan based on the video content
    7. Potential challenges they might face and how to overcome them
    
    Your report should be clear, concise, and capture all the essential information from the video.
    Focus on maintaining the core message while eliminating redundancy and less important details.
    Format the report in Markdown for better readability.
    
  expected_output: >
    A comprehensive, well-structured Markdown report of the YouTube video with the requested sections.
    The report should be clear, concise, and capture all the essential information.
    
