classify_video:
  description: >
    Your task is to classify the YouTube video content based on its transcription.
    
    You will receive the transcription of the YouTube video as input.
    Here is the transcription:
    {transcript}
    
    Please classify this video into one of the following categories:
    - Technology
    - Business
    - Education
    - Health & Wellness
    - Science
    - Finance
    - Personal Development
    
    Provide a brief explanation for your classification choice, highlighting key terms or themes
    from the transcript that support your decision. If the video spans multiple categories,
    choose the most dominant one and mention the secondary categories in your explanation.

  expected_output: >
    A clear classification of the video into one of the specified categories, along with
    a brief explanation justifying the classification based on the transcript content.

summarize_content:
  description: >
    Here is the YouTube video transcription:
    {transcript}

    Create a concise executive summary of the YouTube video transcript, including:

    - TL;DR: Briefly summarize the video's core message in 3-4 clear sentences.
    - Key Points: Provide a bullet-point list (max 5 points) of the most critical takeaways.

  expected_output: >
    Concise, structured executive summary featuring a succinct TL;DR and essential key points.

analyze_content:
  description: >
    Here is the YouTube video transcription:
    {transcript}

    Provide concise, efficient notes analyzing critical insights from the video content, including:

    - Main concept, product, or service discussed
    - Intended audience and relevance
    - Unique points or value propositions
    - Significant technical or practical details

    Include brief, relevant quotes or examples for clarity.

  expected_output: >
    Clear, broadly applicable notes suitable for efficient study and quick comprehension.

create_action_plan:
  description: >
    Based on the provided YouTube video transcription, you are tasked with creating a strategic action plan.
    Here is the YouTube video transcription:
    {transcript}

    Generate concise and actionable advisor notes outlining:

    - 3-5 straightforward recommendations
    - Key resources needed (briefly stated)
    - Clearly defined anticipated outcomes
    - Potential challenges accompanied by simple solutions

    Each recommendation should be direct, practical, and easy to implement immediately.

  expected_output: >
    Direct, actionable advisor notes clearly outlining recommendations, resources, outcomes, and succinct solutions to potential challenges.

write_report:
  description: >
    Here is the YouTube video transcription:
    {transcript}

    Use the classification from the Classify Video task.
    Use the summary from the Summarize Content task.
    Use the analysis from the Analyze Content task.
    Use the action plan from the Create Action Plan task.
    
    Prepare a succinct, high-quality Markdown report (maximum 750 words) clearly summarizing:

    - Classification
    - Crisp TL;DR
    - Key Points
    - Concise Analysis Notes
    - Direct Advisor Recommendations and Action Plan
    - Potential Challenges and Simple Solutions

    Prioritize clarity, readability, and brevity, eliminating redundancy to create superior quality, highly effective notes.

  expected_output: >
    A structured Markdown report crafted as concise, top-tier notes optimized for immediate understanding and practical application.